### ISSUE TITLE
ITO investors can't legally be allowed to see tokens in their wallets yet

### ISSUE THREAD

**Issue by Virgil3** [threefoldfoundation/app_backend#109]
Given that the ITO investors investment is a convertible loan which they have to manually exchange into tokens once the PTO has started we can not show any tokens in their wallets for now. This is clearly stated in the Investor Agreement but as always people do not read all T&Cs. Andreas suggests to use the TF App news section to tell ITO investors.

In their wallet we can put "your convertible loan value is $xxx". Exact wording has to be approved by legal.

Once a CNA has been processed, we can display the amount in the user's wallet. This requires some work from the IYO and the TF team for the backend implementation (Bart-at-mobicage is a good entry person there), Andreas and Pierre will choose wording.

**Comment by RubenMattan** [comment]
Put on hold until we have a permanent answer

**Comment by dvorkbod** [comment]
To make this more explicit: We are looking at the legal options to do show nr of tokens in amount, by changing the process by which TFF collects money from convertible loans (back) to prepurchases of tokens.

**Comment by dvorkbod** [comment]
"iTFT" make this point moot.
