### ISSUE TITLE
Include persistent, easily consultable payment instructions

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#123]
Users are currently experiencing issues reading contracts and remembering what they read in message flows.

Let's add a persistent message generated after the signing of an agreement that has the details of their order: What to mention, where to transfer.

Such a message should be removed or change once payment has been received by us.

This is somewhat related to the TODO list, but user tailored and customised.

**Comment by RubenMattan** [comment]
Hoster:

Please use the following transfer details
Amount: USD 600 - Bank : Mashreq Bank - IBAN : AE230330000019120028156 - BIC : BOMLAEAD

For the attention of Green IT Globe Holdings FZC, a company incorporated under the laws of Sharjah, United Arab Emirates, with registered office at SAIF Zone, SAIF Desk Q1-07-038/B
Please use the SOXXX as reference.

**Comment by RubenMattan** [comment]
@dvorkbod What message shall we use for investor?

**Comment by dvorkbod** [comment]
Investor:

Please use the following transfer details
Amount: USD XXX - Bank : Mashreq Bank - IBAN : AE230330000019120028156 - BIC : BOMLAEAD

For the attention of Green IT Globe Holdings FZC, a company incorporated under the laws of Sharjah, United Arab Emirates, with registered office at SAIF Zone, SAIF Desk Q1-07-038/B

Payment must be made from a bank account registered to your name. Please use FIRSTNAME LASTNAME AMOUNT iTFT tokens as reference.

**Comment by dvorkbod** [comment]
BTC investor:

Please use the following transfer details
Amount: BTC XXX - wallet 3GTf7gWhvWqfsurxXpEj6DU7SVoLM3wC6A 

Please inform us by email at adnan@greenitglobe.com when you have made payment.
