### ISSUE TITLE
New ITO_flow, add payment options

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#130]
I've copied the buy_tokens_ITO_v2 flow and made v3. It is identical except for offering extra payment options,
EUR, GBP, UAED
Corresponding flow choice variables are
EUR_cur
GBP_cur
AED_cur

Same bank as before, but the account numbers are
AED: AE500330000019120028155
USD : AE230330000019120028156
Euro : AE930330000019120028157
GBP: AE780330000019120032792
We will revise the iTFT token purchase agreement ASAP and link it here.

**Comment by dvorkbod** [comment]
We also still need to decide on conversion rates.

**Comment by dvorkbod** [comment]
We can use the hourly conversion rates and mention those in the contract. The contract is being checked by Pierre.

**Comment by dvorkbod** [comment]
Contract v1.5 is finalised at
https://docs.google.com/document/d/162H9QDswivRNwDhxIDmvodzXNsrNtmR9fuGZKshEE_w/edit#
We will explicitly mention the conversion rates to be used. This implies that the amount of tokens is known at signing time for FIAT purchases, but (still) not for BTC.

**Comment by lucasvanhalst** [comment]
https://github.com/threefoldfoundation/app_backend/commit/24e71d3f2e54cfcd8005b53c130bb55b89dfccb5
