### ISSUE TITLE
friend.rebuild_synced_roles is executed twice

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#132]
Because of the backup version?

![screen shot 2017-09-26 at 06 55 35](https://user-images.githubusercontent.com/17762105/30843173-bd901aca-a287-11e7-8aeb-bd5789e2c11e.png)

**Comment by lucasvanhalst** [comment]
It's the staging server, it's config isn't set properly yet

**Comment by lucasvanhalst** [comment]
Deployed staging
