### ISSUE TITLE
Simplify hoster agreements

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#135]
Everyone who currently bought 120 tokens (at 5 USD) will become eligible to become a hoster at no extra cost. People who already ordered a node will be compensated to give everyone the same benefits of 120 tokens for 600 USD and 6 times 5 tokens = 150 tokens total

This means that the hoster_flow will change - I already prepared most of one as "order_node_v3".

As a current last info message, I put:
> Your order is being processed. Your personalized "Terms and conditions" document is being created. and we are verifying you fulfill all requirements in order to become a hoster. This process can currently take a few days.
You will receive a notification when this is finished, and will be asked to sign it with your PIN code to finalize the agreement.

Some issues remain:

Can we check online straight away prior to generating the agreement that this person has indeed
1) paid for 120 tokens
2) has not ordered a node yet?

If this is possible, we can generate the agreement straigth away and the above text should be amended in app to 
> Your order is being processed. Your personalized "Terms and conditions" document is being created. and we are verifying you fulfill all requirements in order to become a hoster. This process can take a few moments.
You will receive a notification when this is finished, and will be asked to sign it with your PIN code to finalize the agreement.

**Comment by lucasvanhalst** [comment]
- [ ] Check if InvestmentAgreement exists with more than 120 tokens
- [ ] If not, flag for manual check. 
- [ ] Add textfield for error message and a cancel button if user hasn't invested enough yet

**Comment by dvorkbod** [comment]
1) InvestmentAgreements marked as paid for a total of more than 120 tokens worth AND no preexisting Hoster agreement
2) If not, flag for manual check (currently here to support legacy investments made outside the app)
3) error message and cancel ONLY pushed to user after manual check

If 1) is true or 2) manual check agrees, we continue the flow / push a filled in HostersAgreement to the user's app.

**Comment by dvorkbod** [comment]
Current hoster confirmation message at https://github.com/threefoldfoundation/app_backend/blob/master/plugins/tff_backend/bizz/hoster.py#L228

>Thank you for your order.
>Your transaction is waiting confirmation.
> Please use the following transfer details
> Amount: USD 600 - Bank : Mashreq Bank - IBAN : AE230330000019120028156 - BIC : BOMLAEAD
> For the attention of Green IT Globe Holdings FZC, a company incorporated under the laws of Sharjah, United Arab Emirates, with registered office at SAIF Zone, SAIF Desk Q1-07-038/B
> Please use the SO number as reference.

This should change to 

> You have now been approved for hosting duties!
> We will keep you updated of the Node shipping process through the app.

**Comment by dvorkbod** [comment]
Also, I guess this means we need to update the todo lists.

**Comment by lucasvanhalst** [comment]
Does this mean we can remove the 'pay' step from the todo list, and remove the 'Mark as paid' button in the dashboard?

**Comment by dvorkbod** [comment]
Yes indeed!
