### ISSUE TITLE
Wallet on Dashboard

### ISSUE THREAD

**Issue by RubenMattan** [threefoldfoundation/app_backend#142]
- see list of users + search
- detail of user for transaction history + balance of tokens

payment admins should be able to grant tokens in detail page of a user

**Comment by RubenMattan** [comment]
History should loop over ThreeFoldPendingTransaction

**Comment by RubenMattan** [comment]
Granting tokens should ask for:
- token type
- sign date
- memo

**Comment by RubenMattan** [comment]
for now username only search is ok, we can extend later

**Comment by lucasvanhalst** [comment]
@RubenMattan 
>History should loop over ThreeFoldPendingTransaction

Sure this shouldn't be `ThreeFoldTransaction` ?

**Comment by RubenMattan** [comment]
No we also want to see the pending transactions & the failed ones (the ThreeFoldTransaction is only updated once in a while)

**Comment by lucasvanhalst** [comment]
Skipping the username search since I'm assuming the CRM already has functionality for this
