### ISSUE TITLE
"Live" conversion rates for all currencies

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#146]
Buy_tokens_ITO_v4 on staging has been prepared to allow for using live currency conversion rates for all currencies.
Much like the current 3 version where EUR, GBP to USD are updated hourly and incorporated in the contract, we'll start doing the same for the BTC stuff.

Are we able to show these "live" conversion rates somewhere in the flow? If so, we should use that to calculate the amount due after the number of tokens / order size has been entered.

This will also require an updated contract, which Pierre will be able to greenlight once the above questions have been answered.

**Comment by lucasvanhalst** [comment]
https://github.com/threefoldfoundation/app_backend/pull/149 some messages in the flow probably need to be updated (on staging server)

**Comment by dvorkbod** [comment]
Messages seemed fine in the text boxes. Time to test it on staging!
