### ISSUE TITLE
Failed to populate intercom user

### ISSUE THREAD

**Issue by RubenMattan** [threefoldfoundation/app_backend#151]
unable to create addresses from value: [{u'city': ***', u'street': u'***', u'country': u'Belgi\xeb', u'label': u'main', u'other': u'', u'postalcode': u'***', u'nr': u'***'}]: val_factory: Unable to instantiate } from types [<class 'plugins.its_you_online_auth.libs.itsyouonline.Address.Address'>]. Exceptions: ["'ascii' codec can't encode character u'\\xeb' in position 5: ordinal not in range(128)

**Comment by lucasvanhalst** [comment]
964873f39b1c41e3cd564188a20066be2a9810b9
