### ISSUE TITLE
Add payment reference to token purchases

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#152]
People want to have a payment reference to their token purchases.
Can we use the reference "IYO_ID-date-randomstring"?
This payment reference than needs to be in the TODO list and every possible place, and integrated with the CRM.

**Comment by RubenMattan** [comment]
This message is sent after they signed the agreement.


Please use the following transfer details
Amount: %(currency)s %(amount)s - Bank : Mashreq Bank - IBAN : %(iban)s - BIC : BOMLAEAD

For the attention of Green IT Globe Holdings FZC, a company incorporated under the laws of Sharjah, United Arab Emirates, with registered office at SAIF Zone, SAIF Desk Q1-07-038/B

Payment must be made from a bank account registered under your name. Please use "FIRSTNAME LASTNAME AMOUNT iTFT" as reference.

**Comment by lucasvanhalst** [comment]
I suggest we ditch the 'randomstring' part of the reference since it will already be pretty long

**Comment by lucasvanhalst** [comment]
And what date do we use, the creation date or the date the agreement was signed?
