### ISSUE TITLE
Document signatures

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/app_backend#153]
Copy of https://docs.greenitglobe.com/ThreeFold/proj_onboarding_tools/issues/66

1. When you go to ItsYou.Olnie See ->
2. And download signed document,
3. It is without any signatures (only printed name on it) like its a blank unsigned document. It is quite confusing.

Proposition:

1. Write in some artistic font full name of the client.
2. Sign the Text of The Agreement with user's Private Key.
3. Add Signature to the bottom of the document (see example of docusign)
4. Upload signed document to IPFS

**Comment by dvorkbod** [comment]
Related https://docs.greenitglobe.com/ThreeFold/proj_onboarding_tools/issues/66

**Comment by dvorkbod** [comment]
Closed, duplicate
