### ISSUE TITLE
Review app for mention of "investment" word.

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#157]
We still use the word "investment" here and there in the app. Flow v3 seems clean in the designer though.
This is a definite no-no.
Emails are also to be doublechecked, Lucas already spotted some issues there.
<img width="181" alt="screen shot 2017-10-03 at 14 39 41" src="https://user-images.githubusercontent.com/26708761/31125510-cf46787e-a848-11e7-9cf9-9452ef582bb9.png">
<img width="187" alt="screen shot 2017-10-03 at 20 13 44" src="https://user-images.githubusercontent.com/26708761/31141343-700fdcea-a877-11e7-82d2-7313a5590f68.png">

**Comment by lucasvanhalst** [comment]
What word should be used then?

**Comment by dvorkbod** [comment]
Purchase agreement for a document

Purchase tokens for the action

Token holder for someone who bought tokens

**Comment by lucasvanhalst** [comment]
This also includes the contracts I assume? Title of those is `Internal Token Offering - Investment Agreement`

**Comment by lucasvanhalst** [comment]
@dvorkbod can you check PR #169 and see if everything is correct?
