### ISSUE TITLE
Process ITO onboarding flow

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#16]
See #14
- [x] Present Convertible Note Agreement (CNA), ask user to sign. Ideally, this CNA is pre-filled with the user info and selected amounts and currency. This implies a new file for every user, to be linked via IYO.SEE.
- [ ] Mail user a copy of the amount owed and payment instructions (to be payed within a week?). Behind the scenes, update our database of expected sales (push info to Tierion?) and generate an invoice for external use. If personalised CNA was not yet generated in step 4, we have to send one (manually) here.
- [x] When money arrives, inform user, update token total and push info to Tierion #23

- [x] Also, add user to the "investor" role and iyo suborg

**Comment by RubenMattan** [comment]
# Step 1
- Generate PDF with custom info
- Store PDF on IPFS
- Send sign form to user 
- Add user to investor group

The other things are still not decided yet

**Comment by dvorkbod** [comment]
Current version of the CNA:
https://docs.google.com/document/d/1F9MUq78xZslxI7uUGMmiehz6STRX4y9deAR2KqgrcK0/edit
I signaled to legal (and Kristof) that the information therein is outdated: It mentions "50% discount on PTO close", instead of 5$ equivalent per token.

**Comment by dvorkbod** [comment]
Apparently, the "5$ per token" message was incorrect, and the "50% discount" is correct.

**Comment by bart-at-mobicage** [comment]
TBD: link to odoo? structured memo?

**Comment by dvorkbod** [comment]
1) 5$ per token is back. 50% discount is out. All contracts up for review.
2) smaller investments (less than 10K euro) won't need a paper contract for now. Bigger ones we will mail out a contract. No need to explicitly inform users for now, we can decide when and if to mail those out behind the scenes.

**Comment by dvorkbod** [comment]
Pierre reviewed the contracts two days ago, these should be OK now.
Current contracts are "version 1.2"
