### ISSUE TITLE
Minimal "make reservation" functionality in the app

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#182]
In order to have already functional / spendable tokens, we need to have a minimal "make a reservation" functionality in the app.

This functionality gets exposed once you have tokens.

It should allow you to choose a type of "object" to reserve, a location and a duration.

For now we will require the following specification in a reservation
- which type of object:
> 1. Virtual machine or
> 2. Kubernetes environment
- which location:
> 1. Belgium
> 1. Sweden
> 1. Russia
- start and end date.

We will manually contact users once they have entered a reservation request and discuss pricing details.

The texts in the front-end can be placeholders (I will fill them in later), in the backend a crm entry can be created or just an email can be sent to Sabrina or Jacques. This will not be the final form of such reservation (requests), so let's not go overboard on the crm integration.

**Comment by dvorkbod** [comment]
Received clarity on locations and services offered, updated above.

**Comment by dvorkbod** [comment]
Reservation flow updated, is ready to test.
Currently only I will receive the email results.

**Comment by dvorkbod** [comment]
Bart, i assigned you to do an independent test of the flow. TIA!

**Comment by bart-at-mobicage** [comment]
TODO:
- [ ] rogerthat-backend: allow setting `qualified_identifier` in the response of `friend.register`
- [ ] tff-backend: set `qualified_identifier` (= display email) in `friend.register`
- [ ] rogerthat-backend: use `qualified_identifier` (if set) in the flow result emails.

**Comment by dvorkbod** [comment]
Right now, I have deliberately kept the payment for this service unspecified. I would suggest to implement a "free fair use policy" for iTFT holders.

Only if we want to have some experience with paying reservations, i would suggest to implement a "shadow/virtual credit balance" for users, which we can manage to keep track of this free fair use.

**Comment by dvorkbod** [comment]
@bart-at-mobicage , can we push this out / live now?

**Comment by bart-at-mobicage** [comment]
Ok, will put it live

**Comment by sabrinasadik** [comment]
Why is it called 'make a reservation'? I suggest to rename it to 'reserve capacity' - we're not a restaurant..

**Comment by dvorkbod** [comment]
Good call, Sabrina 👍 
Also, we restricted to only Kubernetes environments for now, as per the latest communications from Kristof.
