### ISSUE TITLE
Always generate livechat with user

### ISSUE THREAD

**Issue by lucasvanhalst** [threefoldfoundation/app_backend#184]
After registration:
- start chat with user
- store chat id in user data (support_chat_id)

The 'live chat' menu item should open a branding which reads the support_chat_id and opens that chat (and closes the branding)

**Comment by bart-at-mobicage** [comment]
The message of the first chat message needs to be

> Welcome to the ThreeFold Foundation app.
> If you have questions you can get in touch with us through this chat.
> Our team is at your service during these hours:
> 
> Sunday: 07:00 - 15:00 GMT +1
> Monday - Friday:  09:00 - 17:00  GMT +1
> 
> Of course you can always ask your questions outside these hours, we will then get back to you the next business day.

**Comment by lucasvanhalst** [comment]
todo: deploy to production and re-run ensure_intercom_users migration
