### ISSUE TITLE
Global stats mini app

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#20]
sort of progress chart
* amount of tokens raised since june 2017
* value today
* in dollars: total tokens x value today

For now these values will be adjustable by admins on a webpage, later on this will come from an exchange

**Comment by bart-at-mobicage** [comment]
Copied from #20
> Related: Define current token value. Will probable come from an exchange, such as kraken.
> Before such trading is enabled, the token value will probably be the current sale price.

**Comment by dvorkbod** [comment]
In the current plan, we will be running our own exchange and set our own pricepoint.
