### ISSUE TITLE
Start KYC procedure for old investment agreements / node orders

### ISSUE THREAD

**Issue by lucasvanhalst** [threefoldfoundation/app_backend#200]
The KYC procedure needs to be started for old node orders (via the app _and_ not via the app) and investment agreements.

Check with sabrina for those.

**Comment by dvorkbod** [comment]
I think this one is finished now. Checking with Sabrina.

**Comment by sabrinasadik** [comment]
KYC procedure is in progress for everyone who downloaded the app, need to check who of the first investors didn't install the app yet - contact them to help with installing & KYC procedure.

**Comment by lucasvanhalst** [comment]
An applicant has been created for all of them, filter on 'KYC flow finished' here https://tff-backend.appspot.com/users
