### ISSUE TITLE
Exception in global_stats.update_currencies 

### ISSUE THREAD

**Issue by RubenMattan** [threefoldfoundation/app_backend#204]
```python
plugins/tff_backend/bizz/global_stats.py", line 76, in _get_currency_conversions
    result = filter(lambda r: r.id == '%sUSD' % currency.currency, currency_result.results.rate)[0]
AttributeError: 'NoneType' object has no attribute 'rate'
```

**Comment by bart-at-mobicage** [comment]
> The new download issue which began 11/01/17 and returning an error 999 for most users is currently being investigated and we hope to have it resolved soon.


https://forums.yahoo.net/t5/Yahoo-Finance-help/Is-Yahoo-Finance-API-broken/td-p/250503/page/25

**Comment by lucasvanhalst** [comment]
@dvorkbod you're still able to manually change the conversion ratings here https://tff-backend.appspot.com/global-stats/iTFT

**Comment by lucasvanhalst** [comment]
Doesn't seem like it will be fixed anytime soon, we'll have to find another api
