### ISSUE TITLE
missing tokens from one user's wallet

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#212]
Apparently, Rik Van Lier his tokens have disappeared from his wallet.
No further info at this point.

Rik's message:
>Hi, I bought 29/09/'17 iTFT (€500) and i can not see my iTFT in my wallet anymore. please make them visible again.-Rik

**Comment by RubenMattan** [comment]
IYO username: 'rik_van lier_1'
Token count: 117,64

**Comment by dvorkbod** [comment]
Thanks for the speedy followup Ruben. Any transaction made in that wallet over the weekend?

**Comment by RubenMattan** [comment]
No that user only has 1 transaction and dates back to Tuesday, 24 October 2017 09:00:12 GMT

**Comment by dvorkbod** [comment]
Hm. Is the most plausible explanation that he is misremembering his token count?

**Comment by dvorkbod** [comment]
500 euro worth of tokens is about 117, so that's good news.

**Comment by RubenMattan** [comment]
The user reinstalled the app, however there is a bug in rogerthat that does not handle reinstalls correctly.

Will resolve this bug asap.
