### ISSUE TITLE
Make node status visible to hosters in their app

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#216]
Have functionality in the app to allow hosters to check on their node status, as this is a recurring question.

**Comment by dvorkbod** [comment]
Assigned milestone corresponding to communication from Zoom meeting 14th of November

**Comment by lucasvanhalst** [comment]
Can you create a spec for this so we can get started? 
Like, what needs to be shown (number of running vms, energy usage, ..?) and how can we get this information

**Comment by dvorkbod** [comment]
No clue how to get this information, as I have zero experience (pun intended, sadly) interfacing with a zero-node.

I guess users could be interested in:
Uptime
Network traffic during past 30 days
Idle time / busy time
Current workload: running VM's, Kubernetes, etc.
Energy usage
Latency w.r.t. the zero-tier network to serve as proxy for connection quality?

For a first version, uptime, network traffic and idle/busy time could suffice.

**Comment by lucasvanhalst** [comment]
Status -> /nodes/{nodeid} 'status'
Uptime -> /nodes/{nodeid}/info 'uptime'  /  'bootTime'
Network traffic -> /nodes/{nodeid}/stats -> 'network.packets.tx/enp1s0' / 'network.packets.rx/enp1s0'
Network info only available for the last 5 hours
idle/busy time -> /nodes/{nodeid}/states -> sumarry of all 'machine.CPU.percent/{cpunumber}' 

Energy usage not available
Latency not available
