### ISSUE TITLE
Implement design for IYO-based registration in Threefold app [4h]

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#4]

**Comment by bart-at-mobicage** [comment]
![image](https://user-images.githubusercontent.com/17762105/29061998-3d25c912-7c20-11e7-8a40-3e5c969ef303.png)

**Comment by lucasvanhalst** [comment]
![screen shot 2017-08-08 at 17 05 22](https://user-images.githubusercontent.com/6652304/29078867-d991fac4-7c5b-11e7-8793-154b912b6bcb.png)
close enough
