### ISSUE TITLE
To do list for hosters to be shown in the ThreeFold app

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#41]
Once a user has signed the become a hoster agreement, they should have a consultable to do list in their app. Once all to do list steps have finished, the to do list shouldbe archived.

1. Download the ThreeFold app
2. Register on ItsYou.Online
3. Initiate “become a hoster process” in the TF app.
4. Sign the hoster agreement
5. Share shipping address, telephone number, name with shipping company
6. Pay for your tokens
7. Receive confirmation of sending
8. Accept node from delivery service
9. Confirm delivery of node
10. Hook up node to internet and power

1-4 are already checked by the time this To Do list becomes visible
5 and 6 are user actions
7 is an action from our end
8-10 are user actions

Checkmarks are timestamped where possible

**Comment by RubenMattan** [comment]
Design should be something like this

![screen shot 2017-09-01 at 09 27 10](https://user-images.githubusercontent.com/1122760/29959454-b1c69550-8ef7-11e7-98f8-f688fd847a91.png)
