### ISSUE TITLE
Todo list for ITO investors

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#42]
Joining the ITO is on invitation basis only (in theory, this means the "who invited you" step in the flow is superfluous if we make the referer be part of the invitation).

Once a user has accepted the invitation to become an ito investor, they should have a consultable to do list in their app. Once all to do list steps have finished, the to do list should be archived.

Checkmarks are timestamped where possible

1. Get invited to join the IYO.ITOinvites group
2. Accept invitation in IYO
3. Download the ThreeFold app
4. Initiate “join ITO” in the TF app
5. Select currency, amount of tokens
6. Sign the ITO agreement
7. Get added to the IYO.ITOinvestors group
8. Make payment
9. We process payment
10. Tokens are assigned

1-3 are already done by the time the To Do list becomes visible
4-6 are user actions
7 is an action from our end
8 is a useraction
9-10 are our actions (and will happen simultaneously)

**Comment by RubenMattan** [comment]
Design issue:

#60
