### ISSUE TITLE
ITO flow: Add checkbox for non-US citizen message

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#50]
Add 1 choice: "I am no US citizen"
add js validation, checkbox must be selected

**Comment by dvorkbod** [comment]
Yeah, it's in now. But I need to somehow overrule the error message that "you need at least two choices in a single selector". Do we change the message flow designer or make a work-around here?

**Comment by bart-at-mobicage** [comment]
Lucas will update that check

**Comment by dvorkbod** [comment]
Great. I will look into "add js validation, checkbox must be selected" once that is done. Thanks!

**Comment by lucasvanhalst** [comment]
Just use a multi-select widget instead of single-select, with one option. Having only one option is allowed there.
For the validation add this in the textfield that you get when clicking 'Open validation editor':

```javascript
function run(result) {
    if (!result.value) {
        return 'You must select the checkbox';
    }
    return true;
}
```

**Comment by dvorkbod** [comment]
Thanks!
Multi-select done, awaiting fix to be able to change validation code.

**Comment by dvorkbod** [comment]
Done and checked.
