### ISSUE TITLE
ITO flow: remove rates

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#51]
- remove all logic/text related to rates
- don't show amount of tokens in confirmation message. Pierre will formulate the message. I'll add a comment as soon as I get it from Pierre

**Comment by bart-at-mobicage** [comment]
> You are investing X USD. The corresponding amount of Tokens will be determined on the date of the Public Token Offering ('PTO'). As an ITO Investor, you are entitled to a 50% discount on the average value of the Token during such PTO date.

**Comment by dvorkbod** [comment]
Added YEN, GBP, UAED as currencies. Final message updated.
