### ISSUE TITLE
Further integration with IYO

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#68]
In version 0.9.1, we still collect some info in the TF app that should be in IYO.

In the future, whenever we start a generic process / flow (for example "become hoster" / "join ITO"), we check if all needed info has already been entered in IYO. If not, we redirect user to IYO to enter all that info in one single session.

I will pick up this issue in the IYO repo too, to see if this functionality is already offered by IYO.

**Comment by bart-at-mobicage** [comment]
First, we check the user_data to see if we have all data need for this flow. If not, send the user to the IYO auth page with the scopes that we need for this flow, in case we dont have sufficient data from IYO.

**Comment by lucasvanhalst** [comment]
I guess this is done?

**Comment by RubenMattan** [comment]
OAUTH flow step is done

**Comment by RubenMattan** [comment]
Url to refresh had been done https://github.com/rogerthat-platform/plugin-its-you-online-auth/pull/14
