### ISSUE TITLE
Overview of blocking questions

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#77]
- [x] Become investor / hoster #16
  - What has been decided? Does the contract need to be emailed to the user? User signs 2 copies and sends it to us to countersign? We send 1 copy back?
- [x] Payment instructions #63
  - What has been decided? Do we need to mention the payment info in the contract?
- [ ] Node comes online for the first time #64
  - We will ask Maxime how we can know this, such that we can mark it as completed in the TODO-list
- [x] Odoo integration #76
  - We will meet with Pieter/Jacques to see how we can add the Zero-Node orders and user info in Odoo

**Comment by dvorkbod** [comment]
I answered #16 and #63 in those threads yesterday. Are these OK now?

**Comment by bart-at-mobicage** [comment]
Ok, then I think you can close #63. #16 Can be closed as soon as we receive the final version of the contract from Pierre.
