### ISSUE TITLE
Referrals - Invite friends (mini-app)

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#82]
Create a service menu branding (role `threefold.users.invited`) name "Invite friends to ThreeFold" (or "Invite to ThreeFold" if the first is too long to fit on 2 lines).

Show 2 options:
- Invite via SMS
- Invite via E-mail

When clicking an option the SMS/E-mail app is opened and pre-filled with the following text.

> Hi,
> 
> I'd like to invite you the ThreeFold community. You can download the Android or iOS app at https://rogerth.at/install?a=${rogethat.user.app_id}
> 
> To become a registered user in the app, you can use my invitation code ${rogethat.user.data.referral_code}.
> 
> Welcome on board!
> ${rogethat.user.data.name || rogethat.user.name}

**Comment by lucasvanhalst** [comment]
Uploaded to the service
