### ISSUE TITLE
Generate and auto-fill (with IYO info) documents for use in IYO.SEE

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#9]
We will need a way to generate and auto-fill (with IYO info) documents for use in IYO.SEE

For example, hosters' contracts https://docs.google.com/document/d/1NRbsXyb705N-VLMP4jC9aYHOZ3eGYmVjvXkmHd3nmn4/edit contain references to hosters names, address, current date and so on.
For IYO.SEE, "signed" copies of such documents should be auto-filled with information known to IYO.

Basically, TF docs to be processed in IYO.SEE have to contain assignable variables in order to generate personalised docs.

**Comment by bart-at-mobicage** [comment]
- first show a message with a summary of the collected IYO data. Add a button to change this info. And a button to accept and continue.
