### ISSUE TITLE
Decide on conversion rates for token prices

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#92]
Tokens are base-priced at 5 USD during ITO.

What about other currencies? What about Bitcoin?
Do we lock it in? Recalculate every day?

**Comment by dvorkbod** [comment]
Kristof was fine with having a manually adjusted conversion factors for the first week.
@bart-at-mobicage , is there a way to have dynamic conversion factors in the flow?

**Comment by bart-at-mobicage** [comment]
@dvorkbod, let's create a new issue for the conversion rate in this repo for the automation.

**Comment by dvorkbod** [comment]
This is now in app and queried when the contract is generated.
