### ISSUE TITLE
Total due: truncation / rounding issues

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#93]
Currently, the placeholder price of tokens in BTC is 0.011 BTC.
When buying 5 tokens, the amount due becomes 0.0550000005 BTC, or something like that. Conversion error?

**Comment by lucasvanhalst** [comment]
I've updated the flow so that it always shows 8 decimals after the comma for BTC and 2 decimals for other currencies

**Comment by dvorkbod** [comment]
@lucasvanhalst  Thanks. I can't verify right now due to broken registry button. Trailing zeros are never shown, I expect?
I checked the code, it's just a hard trunc. Are we sure this is going to fix the issue for bigger orders? If the issue is due to type conversion, can't we still get issues at decimals of higher order?

**Comment by lucasvanhalst** [comment]
@dvorkbod registration should work now

And yes I'll change it so it rounds properly I forgot .toFixed doesn't do that
