### ISSUE TITLE
Unexpected behavior in our database for non-US currency token orders

### ISSUE THREAD

**Issue by dvorkbod** [threefoldfoundation/app_backend#94]
<img width="432" alt="screen shot 2017-09-08 at 10 06 55" src="https://user-images.githubusercontent.com/26708761/30202135-a8de82b4-947d-11e7-958b-98b363aef429.png">
{{ count }} tokens
amount due expressed in US dollars

**Comment by lucasvanhalst** [comment]
that's because that agreement was made before we stored the amount of tokens
