### ISSUE TITLE
I didn't receive an empty wallet after registration

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#96]
There's no wallet :(
![img_4837](https://user-images.githubusercontent.com/17762105/30211076-b006d538-949f-11e7-8cfd-fb6ab67f7f5d.PNG)

**Comment by RubenMattan** [comment]
DNSLookupFailedError: DNS lookup failed for URL: https://tff-backend/api/plugins/tff_backend/v1.0/payment/assets?app_user=****
