### ISSUE TITLE
Mention the TODO list

### ISSUE THREAD

**Issue by bart-at-mobicage** [threefoldfoundation/app_backend#98]
In the confirmation message of the hoster/investor flows (after signing)
ATM there's no confirmation message after the investor flow. Add this as well, based on the hoster flow.

**Comment by RubenMattan** [comment]
### Current hoster confirmation
Thank you. We successfully received your digital signature.We have stored a copy of this agreement in your ItsYou.Online SEE account.

Your order with ID "***" has been placed successfully.
You can check the status of your order using the "Check on node transit" functionality.


### Current investor confirmation
Thank you. We successfully received your digital signature. We have stored a copy of this agreement in your ItsYou.Online SEE account.


How shall we mention the todo list?

**Comment by dvorkbod** [comment]
At least one Todo list has changed, carrying over this issue to 0.9.4

**Comment by dvorkbod** [comment]
Bringing this over to the next milestone due to changed processes to be tracked.
